
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy

  export const environment = {
    production: false,
    baseUrl: 'https://api.openweathermap.org/data/2.5/forecast',
    apiKey: '{SECRET_API_KEY}',
  };
