name: CI / CD for Angular
on:
  push:
    branches: [ "main" ]
  workflow_call:

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     name: Build and Deploy
    
#     steps:
#       - name: Checkout Repo
#         uses: actions/checkout@master

#       - name: Install Dependencies
#         run: npm ci

#       - name: Replace secret
#         uses: cschleiden/replace-tokens@v1
#         with:
#           tokenPrefix: '{'
#           tokenSuffix: '}'
#           files: 'src/environments/environment.prod.ts'
#         env:
#           SECRET_API_KEY: ${{ secrets.API_KEY}}

#       - name: Build
#         run: npm run 
#         # env:
#         #   API_KEY: ${{ secrets.API_KEY }}

#       - name: Deploy to GitHub Pages
#         uses: crazy-max/ghaction-github-pages@v3
#         with:
#           target_branch: gh-pages
#           build_dir: dist/weather-app-angular
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install Dependencies
        run: npm ci

      - name: Replace secret
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '{'
          tokenSuffix: '}'
          files: 'src/environments/environment.prod.ts'
        env:
          SECRET_API_KEY: ${{ secrets.API_KEY}}

      - name: Build
        run: npm run build:prod
        env:
          SECRET_API_KEY: ${{ secrets.API_KEY }}

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: www/weather-app-angular/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
