jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm ci
      - name: Replace secret
      uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: '{'
        tokenSuffix: '}'
        files: 'src/environments/environment.prod.ts'
        env:
          API_KEY: ${{ secrets.API_KEY }}
      - name: Build
        run: npm run build --deploy-url /weather-app/"
        # env:
        #   API_KEY: ${{ secrets.API_KEY }}
